/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/legal-rules/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Зарегистрировать нормативный документ */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Обязателен для всех операций, изменяющих состояние. */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateNormativeDocumentRequest"];
                };
            };
            responses: {
                /** @description Документ зарегистрирован */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NormativeDocument"];
                    };
                };
                400: components["responses"]["ValidationFailed"];
                401: components["responses"]["Unauthenticated"];
                403: components["responses"]["Forbidden"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/legal-rules/documents/{documentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить нормативный документ */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    documentId: components["parameters"]["DocumentId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Документ найден */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NormativeDocument"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/legal-rules/documents/{documentId}/nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Добавить узел документа (глава/статья/пункт) */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Обязателен для всех операций, изменяющих состояние. */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path: {
                    documentId: components["parameters"]["DocumentId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateDocumentNodeRequest"];
                };
            };
            responses: {
                /** @description Узел добавлен */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DocumentNode"];
                    };
                };
                400: components["responses"]["ValidationFailed"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/legal-rules/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список правил */
        get: {
            parameters: {
                query?: {
                    page?: components["parameters"]["Page"];
                    pageSize?: components["parameters"]["PageSize"];
                    category?: components["schemas"]["RuleCategory"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Список правил */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RuleListEnvelope"];
                    };
                };
            };
        };
        put?: never;
        /** Создать устойчивую идентичность правила */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Обязателен для всех операций, изменяющих состояние. */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateRuleRequest"];
                };
            };
            responses: {
                /** @description Правило создано */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Rule"];
                    };
                };
                400: components["responses"]["ValidationFailed"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/legal-rules/rules/{ruleId}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Создать черновик версии правила */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Обязателен для всех операций, изменяющих состояние. */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path: {
                    ruleId: components["parameters"]["RuleId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateRuleVersionRequest"];
                };
            };
            responses: {
                /** @description Черновик версии создан */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RuleVersion"];
                    };
                };
                400: components["responses"]["ValidationFailed"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/legal-rules/rule-versions/{versionId}/dry-run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Проверить черновик версии на исторических фактах (песочница) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    versionId: components["parameters"]["VersionId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DryRunRequest"];
                };
            };
            responses: {
                /** @description Результат сравнения draft-версии с текущей */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DryRunResult"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/legal-rules/rule-versions/{versionId}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Опубликовать версию правила */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Обязателен для всех операций, изменяющих состояние. */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path: {
                    versionId: components["parameters"]["VersionId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PublishRuleVersionRequest"];
                };
            };
            responses: {
                /** @description Версия опубликована, предыдущая — переведена в superseded */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RuleVersion"];
                    };
                };
                409: components["responses"]["Conflict"];
                422: components["responses"]["DomainInvariantViolation"];
                423: components["responses"]["ImmutableResource"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/legal-rules/rules/{ruleId}/effective-version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить действующую версию правила на дату для заданного scope */
        get: {
            parameters: {
                query: {
                    asOf: string;
                    /** @description JSON-строка scope, например {"legalBase":"fps_service"} */
                    scope: string;
                };
                header?: never;
                path: {
                    ruleId: components["parameters"]["RuleId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Найдена ровно одна применимая версия */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RuleVersion"];
                    };
                };
                /** @description Нет применимой версии правила на дату/scope */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/personnel/units": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Создать подразделение */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Обязателен для всех операций, изменяющих состояние. */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateUnitRequest"];
                };
            };
            responses: {
                /** @description Подразделение создано */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Unit"];
                    };
                };
                400: components["responses"]["ValidationFailed"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/personnel/units/{unitId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить подразделение */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    unitId: components["parameters"]["UnitId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Подразделение найдено */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Unit"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/personnel/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Создать должность */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Обязателен для всех операций, изменяющих состояние. */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreatePositionRequest"];
                };
            };
            responses: {
                /** @description Должность создана */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Position"];
                    };
                };
                400: components["responses"]["ValidationFailed"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/personnel/employees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список сотрудников подразделения */
        get: {
            parameters: {
                query?: {
                    unitId?: string;
                    page?: components["parameters"]["Page"];
                    pageSize?: components["parameters"]["PageSize"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Список сотрудников */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EmployeeListEnvelope"];
                    };
                };
            };
        };
        put?: never;
        /** Зарегистрировать сотрудника */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Обязателен для всех операций, изменяющих состояние. */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateEmployeeRequest"];
                };
            };
            responses: {
                /** @description Сотрудник зарегистрирован */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Employee"];
                    };
                };
                400: components["responses"]["ValidationFailed"];
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/personnel/employees/{employeeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить карточку сотрудника */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    employeeId: components["parameters"]["EmployeeId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Сотрудник найден */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Employee"];
                    };
                };
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/personnel/employees/{employeeId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Изменить статус занятости сотрудника */
        patch: {
            parameters: {
                query?: never;
                header: {
                    /** @description Обязателен для всех операций, изменяющих состояние. */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path: {
                    employeeId: components["parameters"]["EmployeeId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ChangeEmploymentStatusRequest"];
                };
            };
            responses: {
                /** @description Статус изменён */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Employee"];
                    };
                };
                422: components["responses"]["DomainInvariantViolation"];
            };
        };
        trace?: never;
    };
    "/personnel/employees/{employeeId}/service-record-entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** История прохождения службы сотрудника */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    employeeId: components["parameters"]["EmployeeId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Список записей истории */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ServiceRecordEntry"][];
                    };
                };
            };
        };
        put?: never;
        /** Добавить запись в историю прохождения службы */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Обязателен для всех операций, изменяющих состояние. */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path: {
                    employeeId: components["parameters"]["EmployeeId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateServiceRecordEntryRequest"];
                };
            };
            responses: {
                /** @description Запись добавлена (append-only) */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ServiceRecordEntry"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/service-calendar/years": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Создать календарный год (черновик) */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Обязателен для всех операций, изменяющих состояние. */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateCalendarYearRequest"];
                };
            };
            responses: {
                /** @description Год создан */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CalendarYear"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/service-calendar/years/{year}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить календарь года */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    year: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Календарь найден */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CalendarYear"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/service-calendar/years/{year}/days": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Массово задать типы дней года */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Обязателен для всех операций, изменяющих состояние. */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path: {
                    year: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SetCalendarDaysRequest"];
                };
            };
            responses: {
                /** @description Дни установлены */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                423: components["responses"]["ImmutableResource"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/service-calendar/years/{year}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Опубликовать календарь года (делает его неизменяемым) */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Обязателен для всех операций, изменяющих состояние. */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path: {
                    year: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Календарь опубликован */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CalendarYear"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scheduling/duty-schedules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Создать проект графика дежурств */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Обязателен для всех операций, изменяющих состояние. */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateDutyScheduleRequest"];
                };
            };
            responses: {
                /** @description График создан (draft) */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DutySchedule"];
                    };
                };
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scheduling/duty-schedules/{scheduleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить график */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    scheduleId: components["parameters"]["ScheduleId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description График найден */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DutySchedule"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scheduling/duty-schedules/{scheduleId}/shifts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Добавить плановую смену в график */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Обязателен для всех операций, изменяющих состояние. */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path: {
                    scheduleId: components["parameters"]["ScheduleId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreatePlannedShiftRequest"];
                };
            };
            responses: {
                /** @description Смена добавлена */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PlannedShift"];
                    };
                };
                /** @description Пересечение смен сотрудника (EXCLUDE-инвариант) */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Problem"];
                    };
                };
                422: components["responses"]["DomainInvariantViolation"];
                423: components["responses"]["ImmutableResource"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scheduling/duty-schedules/{scheduleId}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Утвердить график */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Обязателен для всех операций, изменяющих состояние. */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path: {
                    scheduleId: components["parameters"]["ScheduleId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ApproveScheduleRequest"];
                };
            };
            responses: {
                /** @description График утверждён (неизменяем) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DutySchedule"];
                    };
                };
                422: components["responses"]["DomainInvariantViolation"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scheduling/duty-schedules/{scheduleId}/revise": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Пересмотреть утверждённый график (создаёт новую версию) */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Обязателен для всех операций, изменяющих состояние. */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path: {
                    scheduleId: components["parameters"]["ScheduleId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ReviseScheduleRequest"];
                };
            };
            responses: {
                /** @description Новая версия графика создана */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DutySchedule"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scheduling/units/{unitId}/duty-schedules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Графики подразделения за период */
        get: {
            parameters: {
                query: {
                    periodStart: string;
                    periodEnd: string;
                };
                header?: never;
                path: {
                    unitId: components["parameters"]["UnitId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Список графиков */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DutySchedule"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/time-accounting/timesheets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Открыть табель сотрудника на учётный период */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Обязателен для всех операций, изменяющих состояние. */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateTimesheetRequest"];
                };
            };
            responses: {
                /** @description Табель открыт */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Timesheet"];
                    };
                };
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/time-accounting/timesheets/{timesheetId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить табель (Write-модель, для табельщика/руководителя) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    timesheetId: components["parameters"]["TimesheetId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Табель найден */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Timesheet"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/time-accounting/timesheets/{timesheetId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Зарегистрировать факт (смена/больничный/отстранение/сверхнорма/командировка) */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Обязателен для всех операций, изменяющих состояние. */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path: {
                    timesheetId: components["parameters"]["TimesheetId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ServiceTimeEventRequest"];
                };
            };
            responses: {
                /** @description Факт зарегистрирован */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ServiceTimeEvent"];
                    };
                };
                /** @description Пересечение с уже существующим фактом табеля */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Problem"];
                    };
                };
                /** @description Нарушение бизнес-инварианта (например, overtime_attraction без overtimeOrderId, либо суточный лимит 24ч на сотрудника превышен) */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Problem"];
                    };
                };
                423: components["responses"]["ImmutableResource"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/time-accounting/timesheets/{timesheetId}/corrections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Внести исправление ранее зарегистрированного факта (append-only) */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Обязателен для всех операций, изменяющих состояние. */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path: {
                    timesheetId: components["parameters"]["TimesheetId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateCorrectionEntryRequest"];
                };
            };
            responses: {
                /** @description Исправление зафиксировано */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CorrectionEntry"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/time-accounting/timesheets/{timesheetId}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Утвердить табель периода */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Обязателен для всех операций, изменяющих состояние. */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path: {
                    timesheetId: components["parameters"]["TimesheetId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Табель утверждён, HoursBreakdown зафиксирован */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Timesheet"];
                    };
                };
                423: components["responses"]["ImmutableResource"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/time-accounting/timesheets/{timesheetId}/reopen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Открыть повторно утверждённый табель (для исправления) */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Обязателен для всех операций, изменяющих состояние. */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path: {
                    timesheetId: components["parameters"]["TimesheetId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ReopenTimesheetRequest"];
                };
            };
            responses: {
                /** @description Табель переоткрыт */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Timesheet"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/time-accounting/overtime-orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Зарегистрировать приказ-основание привлечения сверх нормы */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Обязателен для всех операций, изменяющих состояние. */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateOvertimeOrderRequest"];
                };
            };
            responses: {
                /** @description Приказ зарегистрирован */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OvertimeOrder"];
                    };
                };
                409: components["responses"]["Conflict"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/time-accounting/employees/{employeeId}/timesheet-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Сводка табеля сотрудника за период (CQRS Query, read-проекция) */
        get: {
            parameters: {
                query: {
                    periodStart: string;
                    periodEnd: string;
                };
                header?: never;
                path: {
                    employeeId: components["parameters"]["EmployeeId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Сводка найдена */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HoursBreakdown"];
                    };
                };
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/time-accounting/employees/{employeeId}/hours-breakdown-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** История сводок сотрудника по периодам */
        get: {
            parameters: {
                query?: {
                    page?: components["parameters"]["Page"];
                    pageSize?: components["parameters"]["PageSize"];
                };
                header?: never;
                path: {
                    employeeId: components["parameters"]["EmployeeId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description История сводок */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HoursBreakdown"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/time-accounting/units/{unitId}/timesheet-dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Сводный дашборд по подразделению (CQRS Query, агрегация) */
        get: {
            parameters: {
                query: {
                    periodStart: string;
                    periodEnd: string;
                };
                header?: never;
                path: {
                    unitId: components["parameters"]["UnitId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Агрегированные показатели подразделения */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UnitTimesheetDashboard"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/compensation/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Создать дело о компенсации на основании утверждённого табеля */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Обязателен для всех операций, изменяющих состояние. */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateCompensationCaseRequest"];
                };
            };
            responses: {
                /** @description Дело создано (draft) */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CompensationCase"];
                    };
                };
                409: components["responses"]["Conflict"];
                /** @description Табель ещё не утверждён (инвариант 7.1.1) */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/compensation/cases/{caseId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить дело о компенсации */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    caseId: components["parameters"]["CaseId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Дело найдено */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CompensationCase"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/compensation/cases/{caseId}/elections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Зафиксировать выбор формы компенсации сотрудником */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Обязателен для всех операций, изменяющих состояние. */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path: {
                    caseId: components["parameters"]["CaseId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RecordEmployeeElectionRequest"];
                };
            };
            responses: {
                /** @description Выбор зафиксирован */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CompensationCase"];
                    };
                };
                423: components["responses"]["ImmutableResource"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/compensation/cases/{caseId}/finalize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Финализировать дело о компенсации */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Обязателен для всех операций, изменяющих состояние. */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path: {
                    caseId: components["parameters"]["CaseId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Дело финализировано (неизменяемо далее) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CompensationCase"];
                    };
                };
                422: components["responses"]["DomainInvariantViolation"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/compensation/employees/{employeeId}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** История компенсаций сотрудника */
        get: {
            parameters: {
                query?: {
                    page?: components["parameters"]["Page"];
                    pageSize?: components["parameters"]["PageSize"];
                };
                header?: never;
                path: {
                    employeeId: components["parameters"]["EmployeeId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description История найдена */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CompensationCase"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/compensation/regions/{regionUnitId}/forecast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Региональный прогноз затрат на компенсации (CQRS Query, аналитика) */
        get: {
            parameters: {
                query: {
                    periodStart: string;
                    periodEnd: string;
                };
                header?: never;
                path: {
                    regionUnitId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Прогноз рассчитан */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RegionalCompensationForecast"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rest-balance/employees/{employeeId}/balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Текущий остаток дополнительных суток отдыха */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    employeeId: components["parameters"]["EmployeeId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Остаток найден */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RestBalance"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rest-balance/employees/{employeeId}/movements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Журнал движений баланса ДДО */
        get: {
            parameters: {
                query?: {
                    page?: components["parameters"]["Page"];
                    pageSize?: components["parameters"]["PageSize"];
                };
                header?: never;
                path: {
                    employeeId: components["parameters"]["EmployeeId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Список движений */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BalanceMovement"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rest-balance/employees/{employeeId}/consumption-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Подать рапорт на использование дополнительных суток отдыха */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Обязателен для всех операций, изменяющих состояние. */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path: {
                    employeeId: components["parameters"]["EmployeeId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateConsumptionRequestRequest"];
                };
            };
            responses: {
                /** @description Списание проведено */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BalanceMovement"];
                    };
                };
                /** @description Остаток недостаточен (инвариант 8.1.1) */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leave/grants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Предоставить отпуск сотруднику */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Обязателен для всех операций, изменяющих состояние. */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateLeaveGrantRequest"];
                };
            };
            responses: {
                /** @description Отпуск предоставлен */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LeaveGrant"];
                    };
                };
                /** @description Пересечение с существующим отпуском сотрудника */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Problem"];
                    };
                };
                /** @description Нарушение инварианта (например, повторная выдача personal_circumstances_20y — частичный уникальный индекс) */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leave/employees/{employeeId}/grants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список отпусков сотрудника */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    employeeId: components["parameters"]["EmployeeId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Список найден */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LeaveGrant"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leave/grants/{grantId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Получить конкретный отпуск */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    grantId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Отпуск найден */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LeaveGrant"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leave/grants/{grantId}/recall": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Отозвать сотрудника из отпуска */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Обязателен для всех операций, изменяющих состояние. */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path: {
                    grantId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RecallFromLeaveRequest"];
                };
            };
            responses: {
                /** @description Отзыв зафиксирован */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RecallEvent"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Problem: {
            /** Format: uri */
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            traceId?: string;
        };
        /** @enum {string} */
        DocumentType: "federal_law" | "government_decree" | "departmental_order";
        /** @enum {string} */
        RuleCategory: "norm_calculation" | "night_hours_classification" | "holiday_hours_classification" | "overtime_classification" | "conflict_resolution" | "compensation_coefficient" | "leave_entitlement" | "minimum_rest_period";
        /** @enum {string} */
        RuleStatus: "draft" | "published" | "superseded";
        CreateNormativeDocumentRequest: {
            docType: components["schemas"]["DocumentType"];
            regNumber: string;
            /** Format: date */
            adoptedDate: string;
            title: string;
            /** Format: date */
            validFrom: string;
            /** Format: date */
            validTo?: string | null;
        };
        NormativeDocument: components["schemas"]["CreateNormativeDocumentRequest"] & {
            /** Format: uuid */
            id: string;
        };
        CreateDocumentNodeRequest: {
            /** Format: uuid */
            parentNodeId?: string | null;
            /** @enum {string} */
            nodeType: "chapter" | "article" | "paragraph";
            ordinalNumber: string;
            title?: string;
            textContent?: string;
        };
        DocumentNode: components["schemas"]["CreateDocumentNodeRequest"] & {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            documentId: string;
        };
        CreateRuleRequest: {
            code: string;
            category: components["schemas"]["RuleCategory"];
            displayName: string;
            description?: string;
        };
        Rule: components["schemas"]["CreateRuleRequest"] & {
            /** Format: uuid */
            id: string;
        };
        RuleListEnvelope: {
            items: components["schemas"]["Rule"][];
            page: number;
            pageSize: number;
            totalCount: number;
        };
        CreateRuleVersionRequest: {
            /** @description Конкретные значения измерений scope_schema правила */
            scope: Record<string, never>;
            /** Format: uuid */
            legalBasisNodeId: string;
            /** @description Дерево Formula (см. документ Rule Engine) */
            formulaDefinition: Record<string, never>;
            actions: Record<string, never>[];
            /** Format: date */
            validFrom: string;
            /** Format: date */
            validTo?: string | null;
        };
        RuleVersion: components["schemas"]["CreateRuleVersionRequest"] & {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            ruleId: string;
            versionNo: number;
            status: components["schemas"]["RuleStatus"];
            /** Format: date-time */
            publishedAt?: string | null;
            /** Format: uuid */
            publishedBy?: string | null;
        };
        DryRunRequest: {
            /** Format: date */
            historicalPeriodStart: string;
            /** Format: date */
            historicalPeriodEnd: string;
            sampleSize: number;
        };
        DryRunResult: {
            comparedEntities?: number;
            differencesFound?: number;
            sampleDifferences?: {
                /** Format: uuid */
                employeeId?: string;
                oldValue?: number;
                newValue?: number;
            }[];
        };
        PublishRuleVersionRequest: {
            changeReason: string;
        };
        /** @enum {string} */
        ServiceConditionCategory: "normal" | "hazardous_or_dangerous" | "pedagogical";
        /** @enum {string} */
        EmploymentStatus: "active" | "on_leave" | "sick" | "suspended" | "dismissed";
        /** @enum {string} */
        RegimeType: "five_day_week" | "shift_schedule" | "twenty_four_hour_duty" | "unstandardized";
        /** @enum {string} */
        PositionCategory: "operational" | "administrative" | "pedagogical" | "hazardous_technical";
        CreateUnitRequest: {
            code: string;
            name: string;
            /** Format: uuid */
            parentUnitId?: string | null;
        };
        Unit: components["schemas"]["CreateUnitRequest"] & {
            /** Format: uuid */
            id: string;
            hierarchyPath: string;
        };
        CreatePositionRequest: {
            code: string;
            title: string;
            category: components["schemas"]["PositionCategory"];
            defaultRegimeType: components["schemas"]["RegimeType"];
        };
        Position: components["schemas"]["CreatePositionRequest"] & {
            /** Format: uuid */
            id: string;
        };
        CreateEmployeeRequest: {
            personnelNumber: string;
            fullName: string;
            rank: string;
            /** @enum {string} */
            legalBase: "fps_service" | "labor_code";
            serviceConditionCategory?: components["schemas"]["ServiceConditionCategory"];
            /** Format: uuid */
            currentPositionId: string;
            /** Format: uuid */
            currentUnitId: string;
            /** Format: date */
            hiredAt: string;
        };
        Employee: components["schemas"]["CreateEmployeeRequest"] & {
            /** Format: uuid */
            id: string;
            employmentStatus: components["schemas"]["EmploymentStatus"];
            /** Format: date */
            dismissedAt?: string | null;
        };
        EmployeeListEnvelope: {
            items?: components["schemas"]["Employee"][];
            page?: number;
            pageSize?: number;
            totalCount?: number;
        };
        ChangeEmploymentStatusRequest: {
            newStatus: components["schemas"]["EmploymentStatus"];
            /** Format: date */
            effectiveDate: string;
            reason: string;
        };
        CreateServiceRecordEntryRequest: {
            /** @enum {string} */
            eventType: "assignment" | "transfer" | "rank_change" | "dismissal";
            /** Format: date */
            effectiveDate: string;
            /** Format: uuid */
            positionId?: string | null;
            /** Format: uuid */
            unitId?: string | null;
            rank?: string | null;
        };
        ServiceRecordEntry: components["schemas"]["CreateServiceRecordEntryRequest"] & {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            employeeId: string;
            /** Format: date-time */
            recordedAt: string;
        };
        /** @enum {string} */
        DayType: "working" | "weekend" | "holiday" | "pre_holiday";
        CreateCalendarYearRequest: {
            year: number;
        };
        CalendarYear: {
            /** Format: uuid */
            id: string;
            year: number;
            published: boolean;
        };
        SetCalendarDaysRequest: {
            days: {
                /** Format: date */
                day: string;
                dayType: components["schemas"]["DayType"];
            }[];
        };
        /** @enum {string} */
        AccountingPeriodType: "month" | "quarter" | "year";
        /** @enum {string} */
        ScheduleStatus: "draft" | "approved" | "closed";
        /** @enum {string} */
        DutyType: "five_day_week" | "shift" | "twenty_four_hour_duty";
        CreateDutyScheduleRequest: {
            /** Format: uuid */
            unitId: string;
            periodType: components["schemas"]["AccountingPeriodType"];
            /** Format: date */
            periodStart: string;
            /** Format: date */
            periodEnd: string;
        };
        DutySchedule: components["schemas"]["CreateDutyScheduleRequest"] & {
            /** Format: uuid */
            id: string;
            status: components["schemas"]["ScheduleStatus"];
            approvalOrderRef?: string | null;
        };
        CreatePlannedShiftRequest: {
            /** Format: uuid */
            employeeId: string;
            /** Format: date-time */
            startTime: string;
            /**
             * Format: date-time
             * @description Должно быть строго позже startTime (бизнес-инвариант, проверяется на 422, не в JSON Schema)
             */
            endTime: string;
            dutyType: components["schemas"]["DutyType"];
        };
        PlannedShift: components["schemas"]["CreatePlannedShiftRequest"] & {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            dutyScheduleId: string;
        };
        ApproveScheduleRequest: {
            approvalOrderRef: string;
        };
        ReviseScheduleRequest: {
            reason: string;
        };
        /** @enum {string} */
        TimesheetStatus: "open" | "pending_approval" | "approved" | "reopened";
        /** @enum {string} */
        ServiceTimeEventType: "actual_shift" | "sickness" | "suspension" | "overtime_attraction" | "business_trip";
        CreateTimesheetRequest: {
            /** Format: uuid */
            employeeId: string;
            periodType: components["schemas"]["AccountingPeriodType"];
            /** Format: date */
            periodStart: string;
            /** Format: date */
            periodEnd: string;
        };
        Timesheet: components["schemas"]["CreateTimesheetRequest"] & {
            /** Format: uuid */
            id: string;
            status: components["schemas"]["TimesheetStatus"];
        };
        ServiceTimeEventRequest: {
            eventType: components["schemas"]["ServiceTimeEventType"];
            /** Format: date-time */
            startTime: string;
            /** Format: date-time */
            endTime: string;
            /** Format: uuid */
            plannedShiftId?: string | null;
            /**
             * Format: uuid
             * @description Обязателен, если eventType = overtime_attraction (проверяется на 422)
             */
            overtimeOrderId?: string | null;
            businessTripPlace?: string | null;
        };
        ServiceTimeEvent: {
            eventType: "ServiceTimeEvent";
        } & (Omit<components["schemas"]["ServiceTimeEventRequest"], "eventType"> & {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            timesheetId: string;
        });
        CreateCorrectionEntryRequest: {
            /** Format: uuid */
            originalEventId: string;
            reason: string;
        };
        CorrectionEntry: components["schemas"]["CreateCorrectionEntryRequest"] & {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            timesheetId: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: uuid */
            createdBy: string;
        };
        ReopenTimesheetRequest: {
            reason: string;
        };
        CreateOvertimeOrderRequest: {
            orderNumber: string;
            /** Format: date */
            issuedDate: string;
            reason: string;
        };
        OvertimeOrder: components["schemas"]["CreateOvertimeOrderRequest"] & {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            issuedBy: string;
        };
        HoursBreakdown: {
            /** Format: uuid */
            timesheetId: string;
            /** Format: uuid */
            employeeId: string;
            /** Format: date */
            periodStart: string;
            /** Format: date */
            periodEnd: string;
            normHours: number;
            actualHours: number;
            nightHours?: number;
            holidayHours?: number;
            overtimeHours?: number;
            underworkedHours?: number;
            /** Format: uuid */
            computedFromRuleVersionId?: string;
            /** Format: date-time */
            computedAt?: string;
        };
        UnitTimesheetDashboard: {
            /** Format: uuid */
            unitId?: string;
            /** Format: date */
            periodStart?: string;
            /** Format: date */
            periodEnd?: string;
            totalEmployees?: number;
            totalOvertimeHours?: number;
            totalUnderworkedHours?: number;
            pendingApprovalCount?: number;
        };
        /** @enum {string} */
        CompensationCaseStatus: "draft" | "finalized";
        /** @enum {string} */
        CompensationForm: "monetary" | "additional_rest_time";
        CreateCompensationCaseRequest: {
            /** Format: uuid */
            employeeId: string;
            /** Format: uuid */
            timesheetId: string;
        };
        CompensationLine: {
            /** Format: uuid */
            id: string;
            ruleCategory: components["schemas"]["RuleCategory"];
            hoursAmount: number;
            compensationForm: components["schemas"]["CompensationForm"];
            /** Format: uuid */
            legalBasisRuleVersionId?: string;
            /** Format: date-time */
            employeeElectionAt?: string | null;
        };
        CompensationCase: components["schemas"]["CreateCompensationCaseRequest"] & {
            /** Format: uuid */
            id: string;
            status: components["schemas"]["CompensationCaseStatus"];
            lines: components["schemas"]["CompensationLine"][];
        };
        RecordEmployeeElectionRequest: {
            ruleCategory: components["schemas"]["RuleCategory"];
            compensationForm: components["schemas"]["CompensationForm"];
        };
        RegionalCompensationForecast: {
            /** Format: uuid */
            regionUnitId?: string;
            /** Format: date */
            periodStart?: string;
            /** Format: date */
            periodEnd?: string;
            forecastMonetaryHours?: number;
            forecastRestDays?: number;
        };
        /** @enum {string} */
        MovementType: "accrual" | "consumption";
        RestBalance: {
            /** Format: uuid */
            employeeId: string;
            balanceDays: number;
        };
        BalanceMovement: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            employeeId: string;
            movementType: components["schemas"]["MovementType"];
            amountDays: number;
            /** Format: date */
            movementDate: string;
            /** Format: uuid */
            compensationLineId?: string | null;
            /** Format: uuid */
            leaveGrantId?: string | null;
            /** Format: uuid */
            reversedByMovementId?: string | null;
        };
        CreateConsumptionRequestRequest: {
            amountDays: number;
            /** Format: date */
            movementDate: string;
        };
        /** @enum {string} */
        LeaveType: "basic" | "additional" | "personal_circumstances_20y" | "maternity" | "child_care" | "educational";
        /** @enum {string} */
        LeaveStatus: "active" | "recalled" | "completed" | "cancelled";
        CreateLeaveGrantRequest: {
            /** Format: uuid */
            employeeId: string;
            leaveType: components["schemas"]["LeaveType"];
            /** Format: date */
            periodStart: string;
            /** Format: date */
            periodEnd: string;
        };
        LeaveGrant: components["schemas"]["CreateLeaveGrantRequest"] & {
            /** Format: uuid */
            id: string;
            status: components["schemas"]["LeaveStatus"];
            /** Format: uuid */
            entitlementBasisRuleVersionId?: string;
        };
        RecallFromLeaveRequest: {
            /** Format: date */
            recallDate: string;
            /** Format: date */
            effectiveFrom: string;
        };
        RecallEvent: components["schemas"]["RecallFromLeaveRequest"] & {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            leaveGrantId: string;
        };
    };
    responses: {
        /** @description Форма запроса не проходит валидацию (400) */
        ValidationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Отсутствует/просрочен токен (401) */
        Unauthenticated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Роль/scope не даёт доступа к ресурсу (403) */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Ресурс не найден (404) */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Нарушение уникальности/пересечения (409) */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Нарушение бизнес-инварианта домена (422) */
        DomainInvariantViolation: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Попытка изменить неизменяемый ресурс (423) */
        ImmutableResource: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /** @description Обязателен для всех операций, изменяющих состояние. */
        IdempotencyKey: string;
        Page: number;
        PageSize: number;
        EmployeeId: string;
        UnitId: string;
        RuleId: string;
        VersionId: string;
        DocumentId: string;
        ScheduleId: string;
        TimesheetId: string;
        CaseId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
